In [1]:
from tensorflow import keras
from tensorflow.keras import layers


In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.cluster import AgglomerativeClustering

In [1]:
import numpy as np 
import pandas as pd

In [96]:
cpu_speed = np.array([np.random.randint(10,100) / 100 for i in range(1000)])
ram_activatiosn = np.array([np.random.randint(10,100) / 100 for i in range(1000)])

In [97]:
data_set = pd.DataFrame(data={'CPU Speed' : cpu_speed,'Ram Activation' : ram_activatiosn})

In [98]:
data_set['Diks'] = np.array([np.random.randint(10,100) / 100 for i in range(1000)]) 

In [99]:
data_set['Network Activity'] = np.array([np.random.randint(10,100) / 100 for i in range(1000)])

In [100]:
data_set['CPU Status'] = np.array([1 if cpu_speed[i]> 0.7 else 0 for i in range(len(cpu_speed))])

In [101]:
data_set['Ram Status'] = np.array([1 if ram_activatiosn[i] > 0.7 else 0 for i in range(len(ram_activatiosn))])

In [102]:
data_set['Diks Status'] = np.array([1 if data_set['Diks'][i] > 0.7 else 0 for i in range(0,1000)])
data_set['Network Status'] = np.array([1 if data_set['Network Activity'][i] > 0.7 else 0 for i in range(0,1000)])

In [11]:
import mysql.connector

In [12]:
conenct = mysql.connector.connect(
    host='localhost',
    user = 'root',
    password = 'airin123',
    database = 'knight_bot'
)

In [13]:
cursor = conenct.cursor()

In [19]:
data = data_set.values

In [23]:
data_insert = [tuple(row) for row in data]

In [24]:
data_insert

[(0.1, 0.93, 0.75, 0.3, 0.0, 1.0, 1.0, 0.0),
 (0.93, 0.74, 0.16, 0.94, 1.0, 1.0, 0.0, 1.0),
 (0.37, 0.81, 0.97, 0.27, 0.0, 1.0, 1.0, 0.0),
 (0.64, 0.21, 0.82, 0.24, 0.0, 0.0, 1.0, 0.0),
 (0.22, 0.59, 0.89, 0.39, 0.0, 0.0, 1.0, 0.0),
 (0.62, 0.1, 0.28, 0.81, 0.0, 0.0, 0.0, 1.0),
 (0.6, 0.91, 0.83, 0.9, 0.0, 1.0, 1.0, 1.0),
 (0.52, 0.35, 0.14, 0.73, 0.0, 0.0, 0.0, 1.0),
 (0.87, 0.21, 0.36, 0.24, 1.0, 0.0, 0.0, 0.0),
 (0.58, 0.66, 0.16, 0.45, 0.0, 0.0, 0.0, 0.0),
 (0.19, 0.41, 0.12, 0.51, 0.0, 0.0, 0.0, 0.0),
 (0.62, 0.3, 0.48, 0.78, 0.0, 0.0, 0.0, 1.0),
 (0.68, 0.48, 0.67, 0.52, 0.0, 0.0, 0.0, 0.0),
 (0.79, 0.79, 0.95, 0.13, 1.0, 1.0, 1.0, 0.0),
 (0.59, 0.72, 0.67, 0.26, 0.0, 1.0, 0.0, 0.0),
 (0.34, 0.18, 0.76, 0.65, 0.0, 0.0, 1.0, 0.0),
 (0.29, 0.88, 0.79, 0.2, 0.0, 1.0, 1.0, 0.0),
 (0.38, 0.97, 0.26, 0.87, 0.0, 1.0, 0.0, 1.0),
 (0.33, 0.68, 0.77, 0.86, 0.0, 0.0, 1.0, 1.0),
 (0.69, 0.53, 0.28, 0.2, 0.0, 0.0, 0.0, 0.0),
 (0.94, 0.81, 0.49, 0.92, 1.0, 1.0, 0.0, 1.0),
 (0.92, 0.22, 0.28, 0

In [21]:
query_add = "INSERT INTO hw_data (CPU_Speed,Ram_Activity,Diks,Network_Activity,cpu_status,ram_status,diks_status,network_status) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)"

In [25]:
cursor.executemany(query_add,data_insert)

In [26]:
conenct.commit()

In [27]:
cursor.close()
conenct.close()

In [103]:
data_set

CPU Speed  Ram Activation  Diks  Network Activity  CPU Status  \
0         0.63            0.53  0.62              0.23           0   
1         0.71            0.65  0.75              0.27           1   
2         0.26            0.49  0.81              0.21           0   
3         0.59            0.32  0.95              0.56           0   
4         0.98            0.10  0.97              0.40           1   
..         ...             ...   ...               ...         ...   
995       0.77            0.82  0.16              0.85           1   
996       0.54            0.26  0.98              0.19           0   
997       0.59            0.44  0.12              0.89           0   
998       0.45            0.91  0.49              0.26           0   
999       0.54            0.48  0.74              0.85           0   

     Ram Status  Diks Status  Network Status  
0             0            0               0  
1             0            1               0  
2             0            1               0  
3             0            1               0  
4             0            1               0  
..          ...          ...             ...  
995           1            0               1  
996           0            1               0  
997           0            0               1  
998           1            0               0  
999           0            1               1  

[1000 rows x 8 columns]

In [104]:
target = np.array(([[data_set['CPU Status']],[data_set['Diks Status']],[data_set['Ram Status']],[data_set['Network Status']]]))

In [29]:
counter = data_set['Ram Status'] + data_set['CPU Status'] + data_set['Diks Status'] + data_set['Network Status']

In [31]:
counter
y = []
for i in range(len(counter)) :
    if counter[i] > 2 :
        y.append(1)
    else :
        y.append(0)

In [44]:
checking_status_Machines = RandomForestClassifier(n_estimators=500,criterion='entropy',max_leaf_nodes=16,verbose=1,min_samples_split=20,min_samples_leaf=10,max_depth=32)

In [41]:
x_train,x_test,y_train,y_test = train_test_split(data_set,y,test_size=0.3,random_state=22)

In [45]:
checking_status_Machines.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done 449 tasks      | elapsed:    0.9s


RandomForestClassifier(criterion='entropy', max_depth=32, max_leaf_nodes=16,
                       min_samples_leaf=10, min_samples_split=20,
                       n_estimators=500, verbose=1)

In [33]:
from sklearn.metrics import classification_report,accuracy_score

In [46]:
y_pred = checking_status_Machines.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       269
           1       1.00      0.61      0.76        31

    accuracy                           0.96       300
   macro avg       0.98      0.81      0.87       300
weighted avg       0.96      0.96      0.96       300



[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 449 tasks      | elapsed:    0.0s


In [48]:
print(accuracy_score(y_test,y_pred))

0.96


In [49]:
import joblib 
joblib.dump(checking_status_Machines,'checking_status_Machines.pkl')

['checking_status_Machines.pkl']

In [13]:
data_set


CPU Speed  Ram Activation  Diks  Network Activity  CPU Status  \
0         0.79            0.46  0.29              0.84           1   
1         0.36            0.30  0.73              0.36           0   
2         0.10            0.72  0.63              0.52           0   
3         0.74            0.16  0.92              0.12           1   
4         0.92            0.21  0.53              0.45           1   
..         ...             ...   ...               ...         ...   
995       0.55            0.38  0.69              0.44           0   
996       0.85            0.40  0.29              0.75           1   
997       0.52            0.50  0.91              0.59           0   
998       0.13            0.94  0.99              0.38           0   
999       0.35            0.93  0.90              0.41           0   

     Ram Status  Diks Status  Network Status  
0             0            0               1  
1             0            1               0  
2             1            0               0  
3             0            1               0  
4             0            0               0  
..          ...          ...             ...  
995           0            0               0  
996           0            0               1  
997           0            1               0  
998           1            1               0  
999           1            1               0  

[1000 rows x 8 columns]

In [17]:
from sklearn.linear_model import LogisticRegression

In [69]:
cpu_checker = LogisticRegression(penalty='l1',verbose=1,solver='liblinear')
ram_checker = LogisticRegression(penalty='l2',verbose=2,warm_start=True)
Disk_checker = LogisticRegression(penalty='l2',verbose=2,warm_start=True)
Network_Checker = LogisticRegression(penalty='l2',warm_start=True)

In [27]:
x_train,x_test,y_train,y_test = train_test_split(data_set['CPU Speed'].values.reshape(-1,1),data_set['CPU Status'].values.reshape(-1,1),random_state=12,test_size=0.25)

In [38]:
cpu_checker.fit(x_train,y_train)

[LibLinear]

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(penalty='l1', solver='liblinear', verbose=1)

In [39]:
y_pred = cpu_checker.predict(x_test)

In [46]:
import joblib

In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       168
           1       1.00      1.00      1.00        82

    accuracy                           1.00       250
   macro avg       1.00      1.00      1.00       250
weighted avg       1.00      1.00      1.00       250



In [47]:
joblib.dump(cpu_checker,'cpu_checker.pkl')

['cpu_checker.pkl']

In [50]:
x_train,x_test,y_train,y_test = train_test_split(data_set['Diks'].values.reshape(-1,1),data_set['Diks Status'].values.reshape(-1,1),random_state=12,test_size=0.25)

In [53]:
Disk_checker.fit(x_train,y_train)

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(verbose=2, warm_start=True)

In [54]:
y_pred = Disk_checker.predict(x_test)

In [56]:
joblib.dump(Disk_checker,'Disk_checker.pkl')

['Disk_checker.pkl']

In [58]:
x_train,x_test,y_train,y_test = train_test_split(data_set['Ram Activation'].values.reshape(-1,1),data_set['Ram Status'],test_size=0.25,random_state=134)

In [60]:
ram_checker.fit(x_train,y_train)

LogisticRegression(verbose=2, warm_start=True)

In [61]:
y_pred = ram_checker.predict(x_test)

In [63]:
joblib.dump(ram_checker,'ram_checker.pkl')

['ram_checker.pkl']

In [67]:
x_train,x_test,y_train,y_test = train_test_split(data_set['Network Activity'].values.reshape(-1,1),data_set['Network Status'].values.reshape(-1,1),test_size=0.25,random_state=10)

In [70]:
Network_Checker.fit(x_train,y_train)

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(warm_start=True)

In [71]:
joblib.dump(Network_Checker,'Network_Checker.pkl')

['Network_Checker.pkl']

In [18]:
ram_info = np.array([np.random.randint(0,2) for i in range(500)])
diks_info = np.array([np.random.randint(0,2) for i in range(500)])
cpu_info = np.array([np.random.randint(0,2) for i in range(500)])
network_info = np.array([np.random.randint(0,2) for i in range(500)])
level_abnormal = np.array([(ram_info + diks_info + cpu_info + network_info)])

In [20]:
level_abnormal.reshape(-1,1)

array([[1],
       [1],
       [2],
       [2],
       [4],
       [0],
       [2],
       [0],
       [2],
       [4],
       [4],
       [0],
       [1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [0],
       [1],
       [2],
       [3],
       [2],
       [1],
       [3],
       [0],
       [2],
       [1],
       [3],
       [1],
       [3],
       [2],
       [0],
       [2],
       [3],
       [2],
       [3],
       [1],
       [2],
       [2],
       [3],
       [1],
       [3],
       [3],
       [0],
       [4],
       [1],
       [3],
       [2],
       [0],
       [1],
       [1],
       [3],
       [2],
       [2],
       [2],
       [3],
       [0],
       [2],
       [1],
       [0],
       [0],
       [2],
       [2],
       [3],
       [1],
       [0],
       [2],
       [3],
       [2],
       [1],
       [3],
       [3],
       [3],
       [1],
       [1],
       [2],
       [2],
       [3],
       [1],
       [2],
       [1],
       [4],
    

In [37]:
y = level_abnormal.reshape(-1,1)

In [38]:
y

array([[1],
       [1],
       [2],
       [2],
       [4],
       [0],
       [2],
       [0],
       [2],
       [4],
       [4],
       [0],
       [1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [0],
       [1],
       [2],
       [3],
       [2],
       [1],
       [3],
       [0],
       [2],
       [1],
       [3],
       [1],
       [3],
       [2],
       [0],
       [2],
       [3],
       [2],
       [3],
       [1],
       [2],
       [2],
       [3],
       [1],
       [3],
       [3],
       [0],
       [4],
       [1],
       [3],
       [2],
       [0],
       [1],
       [1],
       [3],
       [2],
       [2],
       [2],
       [3],
       [0],
       [2],
       [1],
       [0],
       [0],
       [2],
       [2],
       [3],
       [1],
       [0],
       [2],
       [3],
       [2],
       [1],
       [3],
       [3],
       [3],
       [1],
       [1],
       [2],
       [2],
       [3],
       [1],
       [2],
       [1],
       [4],
    

In [12]:
data_set = pd.DataFrame(data={'ram' : ram_info,'diks' : diks_info,'cpu' : cpu_info,'network' : network_info})

In [31]:
x = data_set.values

In [32]:
x

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 1, 1],
       ...,
       [1, 1, 0, 1],
       [1, 0, 1, 1],
       [1, 0, 1, 1]])

In [93]:
abnormal_level = keras.Sequential(
    [keras.Input(shape=(4,)),
     layers.Dense(256,activation='relu',kernel_regularizer=keras.regularizers.l1()),
     layers.Dense(128,activation='relu',kernel_regularizer=keras.regularizers.l2(0.01)),
     layers.Dense(64,activation='relu'),
     layers.Dense(5,activation='softmax')
     ]
)

In [94]:
abnormal_level.compile(loss='sparse_categorical_crossentropy',optimizer=keras.optimizers.Adam(learning_rate=0.0001),metrics=['accuracy'])

In [60]:
abnormal_level.fit(x,y,verbose=1,epochs=500)

Epoch 1/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3706 - loss: 1.5835
Epoch 2/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3549 - loss: 1.5547 
Epoch 3/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3567 - loss: 1.5243 
Epoch 4/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3517 - loss: 1.4991 
Epoch 5/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3838 - loss: 1.4642
Epoch 6/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3412 - loss: 1.4978 
Epoch 7/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3689 - loss: 1.4386 
Epoch 8/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3697 - loss: 1.4706 
Epoch 9/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3758 - loss: 1.4489 
Epoch 10/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3597 - loss: 1.4364 
Epoch 11/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3601 - loss: 1.4461 
Epoch 12/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - 

In [50]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report


In [63]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=12)

In [67]:
Abnormal_clasification = MLPClassifier(hidden_layer_sizes=(256,128,64),activation='relu',solver='adam',learning_rate='invscaling',learning_rate_init=0.0001,verbose=True,max_iter=400)

In [68]:
Abnormal_clasification.fit(x_train,y_train)

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 1.59539217
Iteration 2, loss = 1.58961915
Iteration 3, loss = 1.58432741
Iteration 4, loss = 1.57927963
Iteration 5, loss = 1.57420072
Iteration 6, loss = 1.56943250
Iteration 7, loss = 1.56484855
Iteration 8, loss = 1.56061598
Iteration 9, loss = 1.55660722
Iteration 10, loss = 1.55288250
Iteration 11, loss = 1.54911229
Iteration 12, loss = 1.54564746
Iteration 13, loss = 1.54209989
Iteration 14, loss = 1.53862432
Iteration 15, loss = 1.53543380
Iteration 16, loss = 1.53222373
Iteration 17, loss = 1.52925809
Iteration 18, loss = 1.52602498
Iteration 19, loss = 1.52298625
Iteration 20, loss = 1.52017404
Iteration 21, loss = 1.51717760
Iteration 22, loss = 1.51464885
Iteration 23, loss = 1.51212455
Iteration 24, loss = 1.50930902
Iteration 25, loss = 1.50680943
Iteration 26, loss = 1.50449368
Iteration 27, loss = 1.50212911
Iteration 28, loss = 1.49979858
Iteration 29, loss = 1.49785053
Iteration 30, loss = 1.49587504
Iteration 31, loss = 1.49399607
Iteration 32, los

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(256, 128, 64), learning_rate='invscaling',
              learning_rate_init=0.0001, max_iter=400, verbose=True)

In [70]:
y_pred = Abnormal_clasification.predict(x_test)

In [74]:
from sklearn.tree import DecisionTreeClassifier

In [75]:
abnormal_level_decision = DecisionTreeClassifier()

In [76]:
abnormal_level_decision.fit(x_train,y_train)

DecisionTreeClassifier()

In [77]:
y_pred = abnormal_level_decision.predict(x_test)


In [78]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.17      0.16      0.16        32
           2       0.43      0.71      0.54        48
           3       0.31      0.14      0.19        37

    accuracy                           0.35       125
   macro avg       0.23      0.25      0.22       125
weighted avg       0.30      0.35      0.30       125



c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

In [81]:
data_set ['abnormal_detected'] = level_abnormal.flatten()

In [88]:
data_set = data_set.drop(['abnormal_detected'],axis=1)

In [86]:
level_abnormal = data_set['ram'] + data_set['cpu'] + data_set['diks'] + data_set['network']

In [89]:
level_abnormal = np.array(level_abnormal)

In [91]:
x = data_set.values
y = level_abnormal.reshape(-1,1)

In [95]:
abnormal_level.fit(x,y,verbose=1,epochs=50)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1973 - loss: 4.0881
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3236 - loss: 3.9810 
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5372 - loss: 3.8877 
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4592 - loss: 3.7958 
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4197 - loss: 3.7160 
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3733 - loss: 3.6240
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3383 - loss: 3.5575
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3512 - loss: 3.4714 
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3753 - loss: 3.3920 
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3605 - loss: 3.2965 
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3723 - loss: 3.2444 
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3

In [106]:
t1 = np.array([np.random.randint(0,2) for i in range(1000)])
t2 = np.array([np.random.randint(0,2) for i in range(1000)])
t3 = np.array([np.random.randint(0,2) for i in range(1000)])
t4 = np.array([np.random.randint(0,2) for i in range(1000)])

In [112]:
target = pd.DataFrame(data={'predict1':t1,'predict2':t2,'predict3':t3,'predict4':t4})

In [113]:
target

predict1  predict2  predict3  predict4
0           0         0         0         1
1           1         1         1         1
2           1         1         0         1
3           1         0         1         1
4           1         0         0         1
..        ...       ...       ...       ...
995         1         0         1         1
996         0         1         0         1
997         0         0         1         0
998         0         1         0         1
999         0         0         0         0

[1000 rows x 4 columns]

In [114]:
target = target.values

In [115]:
data_tested = abnormal_level.predict(target)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step


In [116]:
data_tested

array([[0.08401267, 0.6828091 , 0.21704938, 0.01126552, 0.00486326],
       [0.0011687 , 0.00094225, 0.03903582, 0.719497  , 0.23935613],
       [0.00420096, 0.00694549, 0.13882533, 0.71750057, 0.13252757],
       ...,
       [0.11279559, 0.72186846, 0.14688988, 0.01254124, 0.00590483],
       [0.0169459 , 0.11021032, 0.78594536, 0.06603029, 0.02086813],
       [0.23516886, 0.68991446, 0.05998784, 0.00906582, 0.00586295]],
      dtype=float32)

In [117]:
Abnormal_clasification.fit(x,y)

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 1.59508317
Iteration 2, loss = 1.58141025
Iteration 3, loss = 1.56831294
Iteration 4, loss = 1.55558066
Iteration 5, loss = 1.54277150
Iteration 6, loss = 1.53076676
Iteration 7, loss = 1.51881374
Iteration 8, loss = 1.50740606
Iteration 9, loss = 1.49614491
Iteration 10, loss = 1.48577766
Iteration 11, loss = 1.47511299
Iteration 12, loss = 1.46500118
Iteration 13, loss = 1.45513761
Iteration 14, loss = 1.44548638
Iteration 15, loss = 1.43629021
Iteration 16, loss = 1.42714402
Iteration 17, loss = 1.41849200
Iteration 18, loss = 1.40934607
Iteration 19, loss = 1.40037595
Iteration 20, loss = 1.39152946
Iteration 21, loss = 1.38295696
Iteration 22, loss = 1.37461030
Iteration 23, loss = 1.36602321
Iteration 24, loss = 1.35767136
Iteration 25, loss = 1.34949630
Iteration 26, loss = 1.34110640
Iteration 27, loss = 1.33281017
Iteration 28, loss = 1.32442218
Iteration 29, loss = 1.31643249
Iteration 30, loss = 1.30831436
Iteration 31, loss = 1.30025614
Iteration 32, los

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(256, 128, 64), learning_rate='invscaling',
              learning_rate_init=0.0001, max_iter=400, verbose=True)

In [118]:
Abnormal_clasification.predict(target)

array([1, 4, 3, 3, 2, 1, 2, 1, 2, 1, 2, 3, 3, 3, 0, 1, 1, 1, 1, 0, 0, 2,
       2, 3, 3, 2, 1, 1, 0, 4, 3, 1, 3, 2, 1, 3, 3, 2, 1, 0, 2, 0, 1, 2,
       0, 2, 3, 1, 3, 2, 3, 1, 2, 2, 2, 2, 3, 4, 0, 1, 2, 2, 2, 2, 3, 0,
       0, 1, 3, 0, 4, 4, 0, 3, 1, 3, 2, 4, 1, 3, 1, 3, 3, 2, 3, 3, 1, 0,
       4, 1, 2, 1, 4, 3, 3, 4, 2, 4, 3, 3, 1, 4, 1, 2, 3, 2, 1, 1, 1, 3,
       3, 2, 0, 3, 2, 4, 1, 0, 2, 1, 2, 1, 1, 1, 2, 2, 2, 3, 1, 3, 3, 1,
       3, 2, 2, 1, 1, 1, 3, 3, 2, 0, 1, 2, 2, 0, 3, 4, 3, 1, 2, 0, 3, 2,
       2, 1, 3, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 2, 2, 3, 2, 3,
       2, 2, 2, 2, 1, 2, 1, 2, 3, 1, 4, 3, 1, 1, 0, 3, 2, 1, 0, 2, 2, 2,
       1, 0, 1, 1, 2, 3, 3, 2, 1, 1, 4, 3, 2, 4, 1, 3, 3, 2, 3, 1, 2, 1,
       2, 3, 2, 2, 1, 4, 1, 2, 2, 0, 2, 1, 4, 3, 0, 1, 2, 3, 1, 3, 3, 3,
       1, 3, 4, 2, 1, 3, 1, 1, 1, 2, 0, 1, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3,
       3, 3, 1, 2, 2, 4, 1, 2, 3, 2, 4, 1, 2, 1, 4, 4, 1, 3, 1, 2, 2, 2,
       3, 1, 4, 2, 0, 0, 2, 4, 3, 1, 2, 4, 2, 3, 1,

In [119]:
import joblib

In [120]:
joblib.dump(abnormal_level_decision,'abnormal_level_decision.pkl')

['abnormal_level_decision.pkl']

In [4]:
from sklearn.tree import DecisionTreeClassifier

In [7]:
Parameter_destructed = np.array([np.random.randint(1,100) / 100 for i in range(1000)])

In [9]:
Parameter_abnormal = np.array([np.random.randint(0,4) for i in range(1000)])

In [11]:
classification = []
for i in range(len(Parameter_abnormal)):
    if Parameter_abnormal[i] > 2 and Parameter_destructed[i] < 0.75 : 
        classification.append(0)
    else : 
        classification.append(1)

In [14]:
classification = np.array(classification).reshape(-1,1)

In [13]:
dataset = pd.DataFrame(data={'Parameter_destructed' : Parameter_destructed,'Parameter_abnormal' : Parameter_abnormal})

In [15]:
x = dataset.values
y = classification

In [43]:
decision_linear = keras.Sequential(
    [keras.Input(shape=(2,)),
     layers.Dense(256,activation='relu'),
     layers.Dense(128,activation='relu'),
     layers.Dense(64,activation='relu'),
     layers.Dense(1,activation='sigmoid')]
)

In [44]:
decision_linear.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [45]:
decision_linear.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 256)            │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41,985 (164.00 KB)

 Trainable params: 41,985 (164.00 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
y

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
    

In [46]:
decision_linear.fit(x,y,verbose=2,epochs=100)

Epoch 1/100


c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\losses\losses.py:27: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


32/32 - 2s - 72ms/step - accuracy: 0.1630 - loss: 0.0000e+00
Epoch 2/100
32/32 - 0s - 12ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 3/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 4/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 5/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 6/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 7/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 8/100
32/32 - 0s - 3ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 9/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 10/100
32/32 - 0s - 3ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 11/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 12/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 13/100
32/32 - 0s - 3ms/step - accuracy: 0.1620 - loss: 0.0000e+00
Epoch 14/100
32/32 - 0s - 4ms/step - accuracy: 0.1620 - loss: 0.0000e+

In [41]:
testing = np.array(([[0.12,4]]))

In [37]:
testing

array([[0.78, 2.  ]])

In [3]:
from sklearn.svm import SVC

In [4]:
machine_vector = SVC(kernel='sigmoid')

In [5]:
machine_vector.fit(x,y)

NameError: name 'x' is not defined

In [6]:
x_test = np.array([np.random.randint(1,100)/100 for i in range(100)])
x_test2 = np.array([np.random.randint(0,4) for i in range(100)])

In [7]:
target = pd.DataFrame(data={'data1' : x_test,'data2' : x_test2})

In [8]:
target

data1  data2
0    0.89      0
1    0.40      3
2    0.63      1
3    0.97      3
4    0.25      2
..    ...    ...
95   0.90      1
96   0.99      1
97   0.53      3
98   0.27      1
99   0.64      0

[100 rows x 2 columns]

In [54]:
machine_vector.predict(target.values)

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [56]:
import joblib

In [57]:
joblib.dump(machine_vector,'confimer_machine.pkl')

['confimer_machine.pkl']