In [1]:
import numpy as np 
import pandas as pd 
from sklearn.datasets import load_iris,fetch_covtype
from sklearn.decomposition import PCA

In [5]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = load_iris()

In [4]:
x = pd.DataFrame(data=data['data'],columns=data['feature_names'])

In [6]:
stdscl = StandardScaler()

In [12]:
x = stdscl.fit_transform(x)

In [13]:
pca1 = PCA(n_components=2)

In [14]:
x = pca1.fit_transform(x)

In [15]:
x

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [16]:
y = pca1.inverse_transform(x)

In [18]:
x

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [19]:
y = stdscl.inverse_transform(y)

In [21]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
y

array([[5.01894899, 3.51485426, 1.46601281, 0.25192199],
       [4.73846304, 3.03043329, 1.60391283, 0.27207352],
       [4.72013023, 3.19683002, 1.3289608 , 0.16741379],
       [4.66843611, 3.08676967, 1.38417005, 0.18224698],
       [5.01709266, 3.5964018 , 1.34541075, 0.20670563],
       [5.41459038, 3.89749154, 1.70257439, 0.38437671],
       [4.80715241, 3.3624126 , 1.26425682, 0.15298113],
       [4.95263473, 3.40809557, 1.48747414, 0.25252816],
       [4.49194713, 2.88315723, 1.32584895, 0.14077825],
       [4.7579029 , 3.12479954, 1.50719513, 0.23814838],
       [5.23683335, 3.72942146, 1.59077823, 0.32280933],
       [4.88446413, 3.38288441, 1.38833341, 0.20791797],
       [4.66234834, 3.02464414, 1.46116062, 0.2103005 ],
       [4.41151103, 2.97977531, 1.02769524, 0.02052641],
       [5.47717153, 4.0606523 , 1.59283856, 0.35040943],
       [5.70723141, 4.39947056, 1.56362285, 0.36518973],
       [5.35610979, 3.91069814, 1.56758271, 0.32746861],
       [5.05366832, 3.50968866,

In [22]:
datacov = fetch_covtype()

In [25]:
x = pd.DataFrame(data=datacov['data'],columns=datacov['feature_names'])
x

Elevation  Aspect  Slope  ...  Soil_Type_37  Soil_Type_38  Soil_Type_39
0          2596.0    51.0    3.0  ...           0.0           0.0           0.0
1          2590.0    56.0    2.0  ...           0.0           0.0           0.0
2          2804.0   139.0    9.0  ...           0.0           0.0           0.0
3          2785.0   155.0   18.0  ...           0.0           0.0           0.0
4          2595.0    45.0    2.0  ...           0.0           0.0           0.0
...           ...     ...    ...  ...           ...           ...           ...
581007     2396.0   153.0   20.0  ...           0.0           0.0           0.0
581008     2391.0   152.0   19.0  ...           0.0           0.0           0.0
581009     2386.0   159.0   17.0  ...           0.0           0.0           0.0
581010     2384.0   170.0   15.0  ...           0.0           0.0           0.0
581011     2383.0   165.0   13.0  ...           0.0           0.0           0.0

[581012 rows x 54 columns]

In [26]:
Stdscl2 = StandardScaler()

In [27]:
x = Stdscl2.fit_transform(x)

In [29]:
x = pd.DataFrame(data=x,columns=datacov['feature_names'])

In [31]:
y = datacov['target']

In [32]:
from sklearn.neural_network import MLPClassifier

In [33]:
neural_network = MLPClassifier(hidden_layer_sizes=(512,256,128),activation='relu',verbose=True,early_stopping=True)

In [39]:
pca2 = PCA(n_components=10)

In [40]:
x = pca2.fit_transform(x)

In [41]:
x

array([[ 2.43972514, -1.27718078,  0.85059458, ..., -0.61332357,
        -1.49008448, -0.39081182],
       [ 2.45224954, -1.22892306,  1.02092258, ..., -0.59949907,
        -1.49373387, -0.39805197],
       [ 2.72328062, -0.74443172,  0.62631904, ...,  0.35775672,
         0.78955846,  0.17620919],
       ...,
       [-2.05504632, -1.05861261, -0.08263807, ...,  1.45389198,
        -0.89808766,  0.15113906],
       [-2.04695476, -0.75542805,  0.26992498, ...,  1.43050982,
        -0.89858924,  0.16487195],
       [-1.96019442, -0.77283107,  0.22596058, ...,  1.37090402,
        -0.89135802,  0.17609803]])

In [42]:
neural_network.fit(x,y)

Iteration 1, loss = 0.58361206
Validation score: 0.771781
Iteration 2, loss = 0.47558322
Validation score: 0.806237
Iteration 3, loss = 0.41910564
Validation score: 0.834205
Iteration 4, loss = 0.37982460
Validation score: 0.842140
Iteration 5, loss = 0.35067499
Validation score: 0.857027
Iteration 6, loss = 0.32858620
Validation score: 0.864411
Iteration 7, loss = 0.31154076
Validation score: 0.869918
Iteration 8, loss = 0.29723840
Validation score: 0.882465
Iteration 9, loss = 0.28495623
Validation score: 0.879849
Iteration 10, loss = 0.27459896
Validation score: 0.886648
Iteration 11, loss = 0.26578570
Validation score: 0.890744
Iteration 12, loss = 0.25765191
Validation score: 0.892706
Iteration 13, loss = 0.25069553
Validation score: 0.892000


c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:697: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


MLPClassifier(early_stopping=True, hidden_layer_sizes=(512, 256, 128),
              verbose=True)