In [13]:
import numpy as np 
import pandas as pd 
from sklearn.linear_model import Lasso
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [3]:
data_set = fetch_california_housing(as_frame=True)

In [4]:
data_set

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
 ...       ...       ...       ...        ...         ...       ...       ...   
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   
 
        Longitude 

In [6]:
x = data_set.data
y = data_set.target

In [8]:
data_set.target_names

['MedHouseVal']

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=4)

In [14]:
scaler = StandardScaler()

In [15]:
x_train = scaler.fit_transform(x_train)

In [16]:
x_test = scaler.fit_transform(x_test)

In [17]:
x_train

array([[-0.90558433,  0.98416922, -0.85920322, ...,  0.14734458,
        -0.77966454,  0.66605557],
       [-0.18700937,  0.42851166, -0.48393979, ..., -0.05243478,
         0.93586497, -1.45823491],
       [-1.21759097, -0.68280345, -1.61653611, ...,  0.03664886,
        -0.73747939,  0.66105724],
       ...,
       [-0.5667687 ,  0.74603027, -0.58170316, ..., -0.0690922 ,
         0.86555638, -1.32827832],
       [-0.63118331, -0.20652555, -0.5083963 , ..., -0.04096812,
        -0.77966454,  0.61107393],
       [-0.6865225 ,  1.53982677, -0.74502786, ...,  0.03531006,
         0.80462228, -1.15833508]])

In [18]:
lass = Lasso()

In [19]:
lass.fit(x_train,y_train)

Lasso()

In [20]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [21]:
y_pred = lass.predict(x_test)

In [22]:
y_pred

array([2.07388137, 2.07388137, 2.07388137, ..., 2.07388137, 2.07388137,
       2.07388137])

In [23]:
mean_squared_error(y_test,y_pred)

1.307044052688896

In [24]:
mean_absolute_error(y_test,y_pred)

0.907717649991478

In [25]:
r2_score(y_test,y_pred)

-0.00024094442892375056

In [26]:
param_grid = {
    'alpha' : [0.0001,0.001,0.1,1,10,100]
}

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
lasso_cv = GridSearchCV(lass,param_grid,cv=3,n_jobs=-1)

In [29]:
lasso_cv.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=Lasso(), n_jobs=-1,
             param_grid={'alpha': [0.0001, 0.001, 0.1, 1, 10, 100]})

In [30]:
y_pred2 = lasso_cv.predict(x_test)

In [31]:
y_pred2

array([2.07886228, 2.52873603, 1.59777993, ..., 2.29138432, 0.91281782,
       2.75088227])

In [32]:
mean_squared_error(y_test,y_pred2)

0.523056306672942

In [33]:
mean_absolute_error(y_test,y_pred2)

0.5317293289455182

In [35]:
r2_score(y_test,y_pred2)

0.5997209634214397

In [36]:
lasso_cv.best_estimator_

Lasso(alpha=0.001)

In [37]:
lasso3 = Lasso(alpha=0.001)

In [38]:
lasso3.fit(x_train,y_train)

Lasso(alpha=0.001)

In [39]:
lasso3.intercept_

2.0738813655869395

In [43]:
coef = lasso3.coef_

In [41]:
data_set.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [42]:
feature_name = ['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']

In [44]:
feature_name = pd.DataFrame({'Feature_name':feature_name,'Coef' : coef})

In [45]:
feature_name

Feature_name      Coef
0       MedInc  0.835232
1     HouseAge  0.114657
2     AveRooms -0.253414
3    AveBedrms  0.283687
4   Population -0.007764
5     AveOccup -0.044712
6     Latitude -0.887811
7    Longitude -0.858270