In [24]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer
from sklearn import datasets
import matplotlib.pyplot as plt 


In [2]:
x,y = datasets.make_classification(n_features=5,n_classes=2,n_samples=100)

In [3]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [4]:
clf = MLPClassifier(max_iter=5000)
clf.fit(x_train,y_train)

MLPClassifier(max_iter=5000)

In [5]:
y_pred = clf.predict(x_test)

In [6]:
y_pred

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1])

In [7]:
x

array([[-1.02256081e+00,  4.76329592e-02,  1.08158531e+00,
        -3.74242083e-01, -5.23070399e-01],
       [-1.04096898e+00, -1.34148235e-02,  1.77222491e+00,
        -6.51358862e-01, -4.65009265e-01],
       [ 2.33059709e-01,  8.05430139e-02, -1.23745286e+00,
        -1.23988265e+00,  1.95905877e-02],
       [-4.67252303e-01,  1.60671969e-01, -1.01178193e+00,
        -5.96587553e-01, -3.90423106e-01],
       [ 1.83933572e+00, -1.77203963e-01, -9.53215397e-01,
        -1.02612613e+00,  1.04063736e+00],
       [ 1.66723965e+00, -3.71054011e-01,  1.41742604e+00,
         9.08365199e-02,  1.17264204e+00],
       [ 6.06854718e-01,  1.31859772e-02, -1.09132802e+00,
         2.22381705e-01,  2.65238427e-01],
       [ 1.31737900e+00, -3.09834096e-01,  1.30043544e+00,
        -8.45588993e-01,  9.44711613e-01],
       [-1.36703279e+00,  2.52768822e-01, -6.04144335e-01,
         5.70666645e-01, -9.05388030e-01],
       [-1.63754673e+00,  9.76753624e-02,  1.50010660e+00,
         9.10972948e-01

In [8]:
y

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [39]:
nln = MLPClassifier(hidden_layer_sizes=(500),activation='logistic',learning_rate='adaptive',learning_rate_init=0.001,warm_start=True,momentum=1.0,max_iter=5000)

In [40]:
data_set = load_breast_cancer()

In [41]:
df = pd.DataFrame(data=data_set['data'],columns=data_set['feature_names'])
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [12]:
x = df.copy()
y = data_set['target']

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=4)

In [42]:
nln.fit(x_train,y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=500,
              learning_rate='adaptive', max_iter=5000, momentum=1.0,
              warm_start=True)

In [43]:
y_pred = nln.predict(x_test)

In [44]:
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.89      0.88        54
           1       0.95      0.94      0.94       117

    accuracy                           0.92       171
   macro avg       0.91      0.91      0.91       171
weighted avg       0.92      0.92      0.92       171



In [46]:
print(accuracy_score(y_test,y_pred))

0.9239766081871345


In [48]:
data_set2 = datasets.fetch_lfw_pairs()

In [49]:
print(data_set2)

{'data': array([[0.30718955, 0.2875817 , 0.33071896, ..., 0.8196079 , 0.83529407,
        0.84705883],
       [0.3542484 , 0.46535948, 0.5437909 , ..., 0.39215687, 0.42875817,
        0.45882353],
       [0.14379086, 0.1385621 , 0.13725491, ..., 0.22222222, 0.22875817,
        0.22614379],
       ...,
       [0.2627451 , 0.34379086, 0.46013072, ..., 0.22745098, 0.25620916,
        0.30588236],
       [0.4745098 , 0.43398693, 0.44575167, ..., 0.5777778 , 0.50980395,
        0.38562092],
       [0.08888889, 0.07450981, 0.08627451, ..., 0.53333336, 0.5581699 ,
        0.58954245]], dtype=float32), 'pairs': array([[[[0.30718955, 0.2875817 , 0.33071896, ..., 0.47843137,
          0.47450984, 0.47973856],
         [0.2888889 , 0.28235295, 0.34509805, ..., 0.47189546,
          0.44444445, 0.4248366 ],
         [0.29150328, 0.30849674, 0.39477125, ..., 0.4666667 ,
          0.4575164 , 0.42875817],
         ...,
         [0.6156863 , 0.579085  , 0.6418301 , ..., 0.6169935 ,
          0.619607

In [50]:
df2 = pd.DataFrame(data=data_set2['data'])

In [51]:
print(df2)

          0         1         2         3         4         5         6     \
0     0.307190  0.287582  0.330719  0.386928  0.430065  0.460131  0.447059   
1     0.354248  0.465359  0.543791  0.620915  0.686275  0.705882  0.704575   
2     0.143791  0.138562  0.137255  0.115033  0.083660  0.108497  0.145098   
3     0.041830  0.049673  0.073203  0.150327  0.239216  0.288889  0.300654   
4     0.210458  0.210458  0.192157  0.162092  0.207843  0.325490  0.462745   
...        ...       ...       ...       ...       ...       ...       ...   
2195  0.240523  0.256209  0.236601  0.253595  0.261438  0.253595  0.241830   
2196  0.339869  0.386928  0.338562  0.279739  0.301961  0.330719  0.364706   
2197  0.262745  0.343791  0.460131  0.478431  0.467974  0.479739  0.498039   
2198  0.474510  0.433987  0.445752  0.486275  0.441830  0.392157  0.396078   
2199  0.088889  0.074510  0.086275  0.112418  0.134641  0.146405  0.166013   

          7         8         9     ...      5818      5819    

In [53]:
x2 = df2.copy()
y2 = data_set2['target']

In [84]:
nln2 = MLPClassifier(hidden_layer_sizes=(2500),activation='identity',learning_rate='invscaling',learning_rate_init=0.001,max_iter=1000)

In [69]:
x2_train,x2_test,y2_train,y2_test = train_test_split(x2,y2,test_size=0.3,random_state=120)

In [85]:
nln2.fit(x_train,y_train)

MLPClassifier(activation='identity', hidden_layer_sizes=2500,
              learning_rate='invscaling', max_iter=1000)

In [86]:
y_pred = nln2.predict(x_test)

In [87]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [88]:
print(accuracy_score(y_test,y_pred))

0.9181286549707602
